import asyncio, os, base64, json
from dotenv import load_dotenv

load_dotenv('/app/backend/.env')
from emergentintegrations.llm.chat import LlmChat, UserMessage

stories = json.load(open('/tmp/stories.json'))
OUT = '/app/frontend/public/panels'
os.makedirs(OUT, exist_ok=True)
sem = asyncio.Semaphore(4)

STYLE = (
    'manga/manhwa comic book page, 3 dramatic vertical panels, vibrant anime illustration, '
    'cinematic lighting, highly detailed, dynamic action composition, portrait orientation. '
    'ABSOLUTELY NO text, NO speech bubbles, NO words, NO letters, NO watermarks anywhere in the image.'
)

async def gen(s, page):
    async with sem:
        path = f"{OUT}/{s['slug']}-p{page}.png"
        if os.path.exists(path):
            print('SKIP', s['slug'], page, flush=True)
            return
        moment = 'opening scene introducing the characters and world' if page == 1 else 'dramatic climax action scene'
        prompt = f"Create a {STYLE} Story: '{s['title']}' (genre: {s['genre']}). Scene: {s['desc']} Depict the {moment} of this story."
        try:
            chat = LlmChat(api_key=os.environ['EMERGENT_LLM_KEY'], session_id=f"panel-{s['slug']}-{page}", system_message='You are a master manga artist.')
            chat.with_model('gemini', 'gemini-3.1-flash-image-preview').with_params(modalities=['image', 'text'])
            text, images = await chat.send_message_multimodal_response(UserMessage(text=prompt))
            if images:
                with open(path, 'wb') as f:
                    f.write(base64.b64decode(images[0]['data']))
                print('OK', s['slug'], page, flush=True)
            else:
                print('NOIMG', s['slug'], page, flush=True)
        except Exception as e:
            print('FAIL', s['slug'], page, str(e)[:150], flush=True)

async def main():
    await asyncio.gather(*[gen(s, p) for s in stories for p in (1, 2)])
    panels = {}
    for s in stories:
        paths = [f"/panels/{s['slug']}-p{p}.png" for p in (1, 2) if os.path.exists(f"{OUT}/{s['slug']}-p{p}.png")]
        if paths:
            panels[s['slug']] = paths
    with open('/app/frontend/src/data/panels.js', 'w') as f:
        f.write('// Auto-generated by /app/scripts/gen_panels.py — maps story slug to comic page images\n')
        f.write('export const PANELS = ' + json.dumps(panels, indent=2) + ';\n')
    print('DONE', len(panels), 'stories with panels', flush=True)

asyncio.run(main())
